server:
  port: 9091

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: https://reloadly-account-service.herokuapp.com/
          uri: lb://https://reloadly-account-service.herokuapp.com/
          predicates:
            - Path=/account/**
        - id: https://reloadly-transaction-service.herokuapp.com/
          uri: lb://https://reloadly-transaction-service.herokuapp.com/
          predicates:
            - Path=/transaction/**

cloud-gateway-health: https://reloadly-cloud-gateway.herokuapp.com/actuator/health

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:https://reloadly-eureka-server.herokuapp.com/eureka}
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

security:
  signing-key: <signing-key>


management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
app:
  auth-service:
    registrationUrl: http://localhost:8080/auth/user/register
    loginUrl: http://auth-service:8082/oauth/token
    validateUrl: http://localhost:8080/auth/user/validate
    basicAuth: Basic dGVzdDp0ZW1w

  eureka-server: eureka

spring:
  config:
    activate:
      on-profile: docker

server.port: 9191

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  signing-key: <signing-key>

