server:
  port: 9091

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**

eureka-server-host: reloadly-eureka-server.herokuapp.com

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:${eureka-server-host}/eureka}
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

security:
  signing-key: <signing-key>


management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
app:
  auth-service:
    registrationUrl: http://localhost:8080/auth/user/register
    loginUrl: http://auth-service:8082/oauth/token
    validateUrl: http://localhost:8080/auth/user/validate
    basicAuth: Basic dGVzdDp0ZW1w

  eureka-server: eureka

spring:
  config:
    activate:
      on-profile: docker

server.port: 9191

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  signing-key: <signing-key>

